version: '3.5'

services:
  db:
    image: mongo
    ports:
      - "27020:27017"
    networks:
      - proxynet
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8003:8000"
    depends_on:
      - db
    networks:
      - proxynet

networks:
    proxynet:
      name: GamesBI-network
