version: '3.5'

services:
  youtubedb:
    image: mongo
    ports:
      - "27020:27017"
    networks:
      - proxynet
  youtubeweb:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8003:8000"
    depends_on:
      - youtubedb
    networks:
      - proxynet
    environment:
      - COVERALLS_REPO_TOKEN
      
networks:
    proxynet:
      name: GamesBI-network
